### ISSUE TITLE
MSYS2/MINGW integration

### ISSUE THREAD

**Issue by filnet** [vrpn/vrpn#201]
Hi,

I am working on adding a vrpn package to MSYS2/MINGW (https://github.com/Alexpux/MINGW-packages).

I got something working with the latest release (7.33) only to realize that this release is almost three years old ;) and that some of the issues I faced were fixed in current master.

So I was wondering if there is an ETA for a new release ?

**Comment by russell-taylor** [comment]
Thank you for adding this!  You can rebase that version on the current master to bring it up to the current code base.  There is a release candidate that @rpavlik is doing final testing on before we release it.

**Comment by filnet** [comment]
I'll wait for an official release. No urgency...

I was able to build vrpn 7.33 and test_vrpn.exe ran fine.

Note that MSYS2/MINGW is not providing most of the libraries that vrpn supports (NIDAQMX, ViewPoint, etc...). Basic stuff like hidapi, directx is available though.

PS: if you could drop the leading zero in the version it would be great :)

**Comment by filnet** [comment]
Just tested with master, compiled out of the box. Nice !

With 7.33, I had to fix issues around finding hidapi and jsoncpp.

Still, I'll wait for the release. MSYS2/MINGW prefers versions over some git hash.

**Comment by filnet** [comment]
Spoke too fast. Neither 7.34 nor master compile out the box.

I have jsoncpp installed and vrpn finds it. This leads to a link failure when linking vrpn_server.exe :

```
../libvrpnserver.a(vrpn_Tracker_JsonNet.C.obj):vrpn_Tracker_JsonNet.C:(.text+0x849): undefined reference to `Json::Value::operator[](char const*) const'
../libvrpnserver.a(vrpn_Tracker_JsonNet.C.obj):vrpn_Tracker_JsonNet.C:(.text+0x854): undefined reference to `Json::Value::empty() const'
../libvrpnserver.a(vrpn_Tracker_JsonNet.C.obj):vrpn_Tracker_JsonNet.C:(.text+0x879): undefined reference to `Json::Value::isConvertibleTo(Json::ValueType) const'
...
```

By changing the following line in CMakeLists.txt:
`list(APPEND SERVER_EXTRA_LIBS ${JSONCPP_LIBRARIES})`
to
`list(APPEND SERVER_EXTRA_LIBS ${JSONCPP_LIBRARY})`
then the build is successful.

Note that FindJsonCpp.cmake does not set JSONCPP_LIBRARIES (it used to in an older version).

I can submit a PR if the fix is deemed correct.

**Comment by filnet** [comment]
A vrpn package is now available in MSYS2/MinGW.

Thanks for the support.
